### ISSUE TITLE
Force 3rd team planes

### ISSUE THREAD

**Issue by kevATin** [biell/alti-server#14]
Recently I was playing around with creating non-standard maps (map editor won't even let you export your map just because the game mode prefix is missing; worked great with altx-tool after a bit of trial and error).
That way I was able to put bases, powerups and even spawn points of 3 different teams onto a map. Unsurprisingly neither I nor the bots I tested this with were spawning as planes of that 3rd team. But it got me wondering: Would it be possible for the server to force players/bots to spawn as the 3rd or Nth team?
This would obviously mess with the tablist and other team-gui elements, but could it work in theory? Maybe not even have the teams be symmetric, but more like 2 main teams competing, with additional teams of players or just bots with their own separate objectives. Though getting 8-way tbd to work would be amazing of course.

**Comment by biell** [comment]
The base altitude code is very two-team.  The code is litered with exception call-outs for ffa and a 3 team version would be even worse.  I don't think this would be possible.  Not even in ffa, because the second you put a base on your map, altitude won't let the map type be ffa.  The code literally looks at the map, searches for bases, balls, bombs, etc. and uses those items/powerUps to figure out what the game mode really is.  That is why the game works, even if you rename our TBD map to "lobby.altx".

A Chinese Checkers TBD or BALL map would be pretty cool, but I just don't think it is in the cards.

**Comment by kevATin** [comment]
I see, too bad.

Then how about tdm and 1dm with more than 2 teams? The map could be in ffa, while the players are assigned their team's colors. I suppose it won't be possible to prevent them from hurting their own team, but having friendly fire could make it more interesting.
There could be a mode where only kills count, and one where deaths are subtracted from your teams kills, with more than 2 teams that could create interesting dynamics.

The score of each team could be output in the chat every 30 seconds or so, like this:

|Red|Blue|Green|etc
|   9|    11|      6|etc

Hopefully with better formatting, or simply:

Red:9 | Blue: 11 | Green: 6 | etc

If we want to keep it simple.
Maybe the scores could be sorted from best to worst~

**Comment by biell** [comment]
The only two ways things could work are to have 2 teams for all modes except FFA, and no teams (color doesn't matter) for FFA.

In FFA, you can create 3 team colors and have players forcibly assigned to each of the 3.  But, keep in mind that they can kill each other, and things like loopy tracker will indiscriminately target players of the same color.

Interesting bug to keep in mind for FFA, if you are blue, you can't hurt a blue turret, but it can hurt you.  I am sure that would be easy to fix, but the authors won't be putting out another version, so we have to live with the bug.

There are literally hundreds of places the binary relationship of team is coded into altitude.  Two teams is at the core of its programming.

**Comment by kevATin** [comment]
I think I'll try to make (when I have the time) a script that does the following:
ffa_map
disable bots
assign players to one of 9(/n) colors(teams)
set plane spawnpoints in clusters according to their color?
count the kills and deaths of each plane and calculate the total scores for each team in the background;
team kills could be made to neither count as kill nor death, which would create the possibility to kill steal/prevent other teams from getting points, by killing your own players;

That bug seems annoying but I guess it's not that bad.

**Comment by biell** [comment]
My spawn zones should help you with the spawn points, but I haven't tested it much for FFA.  If you find a bug, just work with me and I will see about fixing it.

All the math you want to do will be very easy in a alti+script.  You will just have to add your own `kill` hook.

If you really need turrets, just avoid assigning people to one color and make all the turrets that color.

**Comment by kevATin** [comment]
> If you really need turrets, just avoid assigning people to one color and make all the turrets that color.

Good idea, 8 teams seems more intuitive than 9 anyway. I'll go with brown or pink turrets.

This part here at http://altiplus.glaciated.org/ruin seems to imply that pink turrets are considered as not necessary to be killed by alti+server on coop maps.

> Turrets with a health greater than 10,000 will be ignored. So, if you wish to create a COOP style pink turret, that is allowed. I would recommend keeping it pink, so standard COOP convention can be followed. Otherwise, you may wish to demarcate is in some way to let people know they don't have to destroy it. 

So pink means neutral for turrets? Even though that's implied by /ruin, there doesn't seem to be any mention of that in http://altiplus.glaciated.org/coop Maybe that should be updated/improved.

**Comment by biell** [comment]
pink is just a convention.  All turrets work the same.  The convention on Coop maps is that pink turrets are given so much health that you can't ever kill them.  It is just a convention, and not always followed.  I always follow it, it makes playing easier once you know the convention.  People know what to expect.

That link is specific to my ruin game type.  In ruin, you need to destroy all the structures.  However, I won't count any turrets with a health over 10,000 when calculating which turrets can be skipped to win.  I mention in that document that pink would be the best color to use, because it will be more obvious to Coop players that it doesn't have to be killed.  However, in reality, it is the health being over 10,000 that is used to eliminate the turret from contention

**Comment by kevATin** [comment]
Ah I see; is +10.000hp turrets getting auto excluded from coop destroy-objective a fixed setting? Because that seems like something that'd be good to be configurable via a setting in plus.txt~

Alright then I'll probably use pink for neutral turrets.

**Comment by biell** [comment]
The 10,000 thing is only in my ruin game type, where the objective is to destroy every one of the opponents structures.  That is not the goal in Coop, and often you avoid destroying as many things as possible to get the best time.

I don't think I will mess around with adding a setting for ruin, since nobody really likes it that much anyway.  The only ruin maps are a few I made and a few that Solikos made.  If you find that your game needs ruin maps and you need a higher HP threshold for a turret, I can make it configurable.  But, 10,000 is really high.  To put it into perspective, on ball_coop_jaxx, the turrets have 30,000 health (3 times that number) but the sole purpose of the map is to bang on a turret until it dies, and you have given a bunch of missles and bombs to make it happen.  And, even with all that help, it still takes 5 players a minute to kill the turrets.
