### ISSUE TITLE
Difference between standard and normal gameType

### ISSUE THREAD

**Issue by kevATin** [biell/alti-server#16]
“/set gameType [coop|flag|race|ruin|zone|mdg|1lh|**std**|**normal**]”

In Altitude I believe I remember that you told me that std stood for standard maps that are part of vanilla Altitude. Then what does normal stand for in this context?

**Comment by biell** [comment]
That documentation is old, I will push an update.  It should be:

/set gameType [mapname|std|coop|race|ruin|flag|zone|mdg|1lh|4ball]

Where the old "normal" should now be "mapname".  I realized some time ago that was confusing because "normal" meant to use the normal method of reading the map name and pulling it from there.  This basically hard-codes what the server would have naturally done anyway.

The better thing to do is to "/unset gameType" and let the server read it from the map name each time the map loads.

**Comment by kevATin** [comment]
You haven't yet pushed this update, have you?
Should this issue be kept open so we don't forget about it?

**Comment by biell** [comment]
Pushed to github, along with first iteration of 1fa.

**Comment by kevATin** [comment]
@biell 
Nice

in the readme.md
I think this line

> **/set gameType [mapname|std|coop|race|ruin|flag|zone|mdg|1lh|4ball]**<br>

should also include 1fa between 1lh and 4ball, right?

**Comment by biell** [comment]
I hadn't gotten there yet, because I was still working on the 1fa mode.  It is there now.
