### ISSUE TITLE
altitude.sh Installer Requirements

### ISSUE THREAD

**Issue by kevATin** [biell/alti-server#26]
Back when I first set up altitude on my raspberry pi I quickly discovered that the installer had trouble executing, so I moved the files over from another system.
Now I just saw that you're aware of that too:

> "bash altitude.sh -c", then specify all defaults.

> If this doesn't work, install altitude on a server which does and just rsync it over.

> I have not gotten the installer to work on google compute, for example.

I suppose it's unknown what the cause of some systems succeeding and others failing is, right?

Something that might be interesting; a RPi with the latest Raspbian image fails at running altitude.sh, but the x86 version (in VirtualBox) of Raspbian installs altitude fine.

Is the console output you're getting also like this?

> ./altitude.sh

> Unpacking JRE ...

> Starting Installer ...

> ./altitude.sh: 431: ./altitude.sh: /home/pi/pathTo/altitude.sh.25435.dir/jre/bin/java: Exec format error

Has someone tried to narrow that error down?

**Comment by biell** [comment]
No, but I have seen it a number of times too.  It also happens on a Linux container under a chromebook.

The installer is basically pointless, because it installs the same exact binaries on every Linux system, regardless of how it was executed.  So, I would create one nice raspberry pi install for yourself, then tar it up and use it as the basis for all your future installs.

**Comment by kevATin** [comment]
Yeah that's what I've been doing; except zip instead of tar.
Well too bad~
