### ISSUE TITLE
[Idea] Measure damage on map / Pseudo-Targets via bots

### ISSUE THREAD

**Issue by kevATin** [biell/alti-server#31]
Can you measure damage inflicted via the bomb powerup on a certain spot on the map?
If yes then tell me how and I guess you can ignore the rest of this~

If not, have you thought about spawning bots in spots encapsulated by thin map walls; maybe even have a top layer hide the bot altogether within a base-lookalike texture.
Check for damage inflicted onto the bot, and then act based on that. A health powerup coult replenish the bots hp, except if that could cause the damage measurement to be inaccurate. Highly bouncy walls to make sure the bot doesn't get damaged, and quickly respawn it.

Do you get what I mean? Has anyone tried something like that before? Good idea, bad idea?

**Comment by biell** [comment]
Some of what you are suggesting is very common on Coop maps, since you want to hide the bot from sight.  Take a look at the screenshot for tbd_coop_bunker_buster:  http://altimaps.glaciated.org/tbd_coop_bunker_buster_collapsed.png  and then take a look at the map on Coop+.  The bot is in that bottom right corner, but you can't see it.

Be careful about thin walls, they bots can escape, I am sure you have seen players manage to squeeze between walls before.  A little bit of what you are talking about can be seen on tbd_up.  The idea there is that you can get extra XP if you drop the bomb near the scrolling bots on the bottom:  http://altimaps.glaciated.org/tbd_up_collapsed.png .

When you damage a base, you get a `structureDamage` log entry.  But, that is it, everything else goes with the `kill` log entry.  At the end of a round, there is a stats entry in the `roundEnd` log entry which will tell you all the damage dealt by a player.  Additionally, the `despawn` entry that Xal added will give you the cumulative stats hash.  However, while they are flying around doing damage, there are no updates on total turret or player damage dealt.

**Comment by kevATin** [comment]
Interesting; that's too bad, I would've liked to have damage stats during the game, but I guess kill is good enough.
