### ISSUE TITLE
Enable xx-patch by default?

### ISSUE THREAD

**Issue by kevATin** [biell/alti-server#7]
Wouldn't it make more sense for the xx-patch to be enabled by default, since most people running this server software probably want as many features as possible?

**Comment by biell** [comment]
I am not comfortable making this the default since it changes the altitude delivered code with something 3rd-party (not from Altitude or me).  However, I documented the process to run this in the INSTALL.txt file so that it is obvious that running this is recommended.  This is added in 050d9be7e0d9a27422dab27debdebbac98d89c11
